## Dimensions of of Tensorflow

### One dimensional tensor

In [1]:
import numpy as np
tensor_1d = np.array([1.3, 1, 4.0, 23.99])
print(tensor_1d)

[ 1.3   1.    4.   23.99]


Indexing is the same as python lists

In [2]:
print(tensor_1d[0])

1.3


### Two dimensional Tensors

In [3]:
tensor_2d = np.array([(1,2,3,4),(4,5,6,7),(8,9,10,11),(12,13,14,15)])
print(tensor_2d)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [4]:
tensor_2d[3][2]

14

### Tensor Handling and Manipulations

In [12]:
import tensorflow as tf
import numpy as np

matrix1 = np.array([(2,2,2),(2,2,2),(2,2,2)],dtype = 'int32')
matrix2 = np.array([(1,1,1),(1,1,1),(1,1,1)],dtype = 'int32')

print (matrix1)
print (matrix2)

matrix1 = tf.constant(matrix1)
matrix2 = tf.constant(matrix2)
matrix_product = tf.matmul(matrix1, matrix2)
matrix_sum = tf.add(matrix1,matrix2)
matrix_3 = np.array([(2,7,2),(1,4,2),(9,0,2)],dtype = 'float32')
print (matrix_3)

#matrix_det = tf.matrix_determinant(matrix_3) ## matrix_determinant is depricated, switch to new code
matrix_det = tf.linalg.det(matrix_3)


#with tf.Session() as sess: ## Session() is depricated, switching to new code
#    result1 = sess.run(matrix_product)
#    result2 = sess.run(matrix_sum)
#    result3 = sess.run(matrix_det)
#print (result1)
#print (result2)
#print (result3)

## New Code
tf.print("Matrix Product:")
tf.print(matrix_product)
tf.print("Matrix Sum:")
tf.print(matrix_sum)
tf.print("Matrix Determinate:")
tf.print(matrix_det)

[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[2. 7. 2.]
 [1. 4. 2.]
 [9. 0. 2.]]
Matrix Product:
[[6 6 6]
 [6 6 6]
 [6 6 6]]
Matrix Sum:
[[3 3 3]
 [3 3 3]
 [3 3 3]]
Matrix Determinate:
55.9999924
