Pulled from: https://www.tensorflow.org/tutorials/quickstart/beginner <br/>
In particular this is https://www.tensorflow.org/tutorials/quickstart/beginner <br/>
Use's the Keras (https://www.tensorflow.org/guide/keras/overview) 

#### This short introduction uses <a href="https://www.tensorflow.org/guide/keras/overview">Keras</a> to:

    - Load a prebuilt dataset.
    - Build a neural network machine learning model that classifies images.
    - Train this neural network.
    - Evaluate the accuracy of the model.

#### This tutorial is a <a href="https://colab.research.google.com/notebooks/welcome.ipynb">Google Colaboratory</a> notebook. Python programs are run directly in the browser—a great way to learn and use TensorFlow. To follow this tutorial, run the notebook in Google Colab by clicking the button at the top of this page.

    - In Colab, connect to a Python runtime: At the top-right of the menu bar, select CONNECT.
    - To run all the code in the notebook, select Runtime > Run all. To run the code cells one at a time, hover over each cell and select the Run cell icon.

### Set up TensorFlow

Import TensorFlow into your program to get started:

In [1]:
#import tensorrt
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

2024-05-21 04:02:01.652153: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


TensorFlow version: 2.16.1


### Load a dataset

Load and prepare the MNIST dataset. The pixel values of the images range from 0 through 255. Scale these values to a range of 0 to 1 by dividing the values by 255.0. This also converts the sample data from integers to floating-point numbers:

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


### Build a machine learning model

Build a <a href="https://www.tensorflow.org/api_docs/python/tf/keras/Sequential">tf.keras.Sequential</a> model:

In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


<a href="https://www.tensorflow.org/guide/keras/sequential_model">Sequential</a> is useful for stacking layers where each layer has one input <a href="https://www.tensorflow.org/guide/tensor">tensor</a> and one output tensor. Layers are functions with a known mathematical structure that can be reused and have trainable variables. Most TensorFlow models are composed of layers. This model uses the <a href="https://www.tensorflow.org/api_docs/python/tf/keras/layers/Flatten">Flatten</a>, <a href="https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense">Dense</a>, and <a href="https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dropout">Dropout</a> layers. <br/>

For each example, the model returns a vector of <a href="https://developers.google.com/machine-learning/glossary#logits">logits</a> or <a href="https://developers.google.com/machine-learning/glossary#log-odds">log-odds</a> scores, one for each class.

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.6886557 ,  0.5581003 , -0.35942563, -0.09931029,  0.42984626,
         0.16283825,  0.38603568, -0.03345186, -0.12695028,  0.08354276]],
      dtype=float32)

The <a href="https://www.tensorflow.org/api_docs/python/tf/nn/softmax">tf.nn.softmax</a> function converts these logits to probabilities for each class: 

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.04577086, 0.1592386 , 0.06361682, 0.08251607, 0.14007103,
        0.10724777, 0.13406692, 0.0881334 , 0.08026657, 0.09907194]],
      dtype=float32)

Define a loss function for training using <a href="https://www.tensorflow.org/api_docs/python/tf/keras/losses/SparseCategoricalCrossentropy">losses.SparseCategoricalCrossentropy</a>:

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

The loss function takes a vector of ground truth values and a vector of logits and returns a scalar loss for each example. This loss is equal to the negative log probability of the true class: The loss is zero if the model is sure of the correct class.
<br />&nbsp;<br />
This untrained model gives probabilities close to random (1/10 for each class), so the initial loss should be close to -tf.math.log(1/10) ~= 2.3.

In [8]:
loss_fn(y_train[:1], predictions).numpy()

2.2326136

Before you start training, configure and compile the model using Keras <a href="https://www.tensorflow.org/api_docs/python/tf/keras/Model#compile">Model.compile</a>. Set the <a href="https://www.tensorflow.org/api_docs/python/tf/keras/optimizers">optimizer</a> class to adam, set the loss to the loss_fn function you defined earlier, and specify a metric to be evaluated for the model by setting the metrics parameter to accuracy.

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

### Train and evaluate your model

Use the <a href="https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit">Model.fit</a> method to adjust your model parameters and minimize the loss: 

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.8621 - loss: 0.4753
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9583 - loss: 0.1428
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9674 - loss: 0.1089
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9723 - loss: 0.0882
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9769 - loss: 0.0747


The <a href="https://www.tensorflow.org/api_docs/python/tf/keras/Model#evaluate">Model.evaluate method</a> checks the model's performance, usually on a <a href="https://developers.google.com/machine-learning/glossary#validation-set">validation set</a> or <a href="https://developers.google.com/machine-learning/glossary#test-set">test set</a>.

In [11]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - 955us/step - accuracy: 0.9768 - loss: 0.0767


[0.07671322673559189, 0.9768000245094299]

The image classifier is now trained to ~98% accuracy on this dataset. To learn more, read the <a href="https://www.tensorflow.org/tutorials/">TensorFlow tutorials</a>.
<br/> &nbsp; <br/>
If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[7.6793390e-07, 1.2574103e-08, 3.3460394e-05, 1.7217894e-03,
        2.5024826e-11, 1.1242750e-05, 4.4609715e-14, 9.9821353e-01,
        8.4939006e-07, 1.8349845e-05],
       [3.3119282e-08, 1.4355188e-06, 9.9999809e-01, 2.1350881e-07,
        4.6124929e-15, 2.3581952e-08, 9.2790184e-09, 2.9719960e-14,
        2.0133879e-07, 1.5613985e-14],
       [2.1069566e-06, 9.9678051e-01, 3.3129542e-04, 2.5011628e-05,
        1.6017948e-05, 2.2500690e-05, 9.9518846e-05, 2.2309059e-03,
        4.8583068e-04, 6.3430284e-06],
       [9.9995863e-01, 1.8415207e-09, 1.2948097e-05, 3.5824254e-07,
        1.7207165e-07, 1.5732432e-05, 9.5769738e-06, 1.7492753e-06,
        2.6927237e-08, 8.5806226e-07],
       [1.0297903e-06, 2.7294245e-09, 2.3051641e-06, 2.4559424e-07,
        9.9981338e-01, 8.9006420e-07, 2.6420216e-06, 3.4762466e-05,
        4.6724685e-07, 1.4418938e-04]], dtype=float32)>

### Conclusion

Congratulations! You have trained a machine learning model using a prebuilt dataset using the <a href="https://www.tensorflow.org/guide/keras/overview">Keras</a> API.

For more examples of using Keras, check out the <a href="https://www.tensorflow.org/tutorials/keras/">tutorials</a>. To learn more about building models with Keras, read the <a href="https://www.tensorflow.org/guide/keras">guides</a>. If you want learn more about loading and preparing data, see the tutorials on <a href="https://www.tensorflow.org/tutorials/load_data/images">image data loading</a> or <a href="https://www.tensorflow.org/tutorials/load_data/csv">CSV data loading</a>.